#!/usr/bin/env ruby

HOURS_PER_DAY = 24
DAYS_PER_YEAR = 365.242
HOURS_PER_YEAR = HOURS_PER_DAY * DAYS_PER_YEAR

puts "Hours in a year = #{HOURS_PER_YEAR}"

MINUTES_PER_HOUR = 60
YEARS_PER_DECADE = 10

puts "Minutes in a decade = #{MINUTES_PER_HOUR * HOURS_PER_YEAR * YEARS_PER_DECADE}"
